//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/InputActions/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""PlayerMain"",
            ""id"": ""d5363a85-e2d2-4fdc-8036-b702c1fb07f1"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""168fb7e3-4d8a-4f0c-bb8c-8a984cd592d8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""2e8de126-b687-4f67-8dfe-f1c11dd0e47f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""45016885-d51f-4e64-b6b0-6c10772b0fef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""88def06b-4cad-4557-b060-86b1bfc81cf9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skate"",
                    ""type"": ""Button"",
                    ""id"": ""c3148858-2a79-45c4-b95e-6b1f8dcbb389"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""cc2cafc0-a32e-4d88-bff5-2e2f6cb81139"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sword"",
                    ""type"": ""Button"",
                    ""id"": ""1c735aec-7860-4e33-a44d-8f76a5df9d0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExtraSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""454ce572-b4b1-42c1-ae74-9c6cd0931bd4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""436ebb0f-c797-471f-9fd6-6e0f06897ae5"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""2fd7eec7-521e-41a9-bb5b-7342628100a7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""96a2e4fc-f433-4c2d-aac8-cda4d056691b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""759db9e2-16e2-4e87-97f6-02b965f98be1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""19bdb0d5-3e75-42b8-91b8-7198d2940f13"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2cf6e5df-0e36-493d-a3e5-ddd5939eeb75"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a8fd545b-a50a-453b-8a9d-aac31a6b73ef"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfaa5fe7-53f3-4fa4-b5d8-46d323682199"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95d536a6-a40c-4f35-8a9f-cbe968a81c6e"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83ce46ec-d759-4d97-bd9f-1fe167f9c6e5"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02d746ca-c464-4ad0-9418-5e59e4b5cb13"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30de3681-65a9-4486-bd5a-45b08727aa64"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fa221bd-daad-4de4-b2c5-4e866f77c8b9"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f3f2b3d-df24-483d-8836-e14a7d5e234c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0261b98f-d7a3-42fa-b053-f747c0a46931"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc792c93-82f8-4e39-8643-a1b4729637eb"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5534e6d-8a3f-4b9d-b866-0faf7fdd74b3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af147493-2b8f-4bc3-a377-ce19bc173fa7"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExtraSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CharacterMenuInput"",
            ""id"": ""2015caca-f443-4453-9bc9-b74dbdba0817"",
            ""actions"": [
                {
                    ""name"": ""Stick"",
                    ""type"": ""Value"",
                    ""id"": ""9d2e7db7-d8b9-4777-8d85-3b2e12465c73"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Spartacus"",
                    ""type"": ""Button"",
                    ""id"": ""b0eb42be-0b5a-4e0c-99f6-6d832c2f9eb4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Glassy"",
                    ""type"": ""Button"",
                    ""id"": ""5bb5977e-7035-43d7-ac20-6e937572b3f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dobby"",
                    ""type"": ""Button"",
                    ""id"": ""d1f1bc31-995d-47c8-8f85-72379fca6969"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Guard"",
                    ""type"": ""Button"",
                    ""id"": ""51553149-b0de-4c2b-9c31-e059d47dcb5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lusth"",
                    ""type"": ""Button"",
                    ""id"": ""63c929c0-dcb8-4eb7-b751-0d3c8c09f101"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eve"",
                    ""type"": ""Button"",
                    ""id"": ""c292def6-3370-4aec-94b4-3b112e7d2cb7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Michelle"",
                    ""type"": ""Button"",
                    ""id"": ""dd65162b-5d4c-4e5b-b5af-8c987898f511"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Boss"",
                    ""type"": ""Button"",
                    ""id"": ""3c1c68e7-6dcf-434d-94b7-47a63bbb976c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aj"",
                    ""type"": ""Button"",
                    ""id"": ""d8eaa997-698b-4ce0-9b46-0ca10f1ee243"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mremireh"",
                    ""type"": ""Button"",
                    ""id"": ""c69a75bb-2be3-4aed-b232-485fbefa2f23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ty"",
                    ""type"": ""Button"",
                    ""id"": ""312774fa-666f-4cd5-9b56-290054a16350"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6d4ad014-f1c6-41b3-afc6-16ceb8a7dc1b"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf19af75-853b-4138-b49e-0a527c22c3b4"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spartacus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2d4571c-41a2-4232-af29-7db66b737ed0"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Glassy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""978135b7-20d8-4e51-b2ff-5faea310182c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dobby"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3839b41-081e-410a-b8d5-9fe03113152d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6cc4f66-d7f1-49a6-8530-4d1462451973"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lusth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e41a1c27-cc23-4dd5-ab89-a51c2daefc50"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Eve"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05f0f49d-2b97-46df-9a72-9f76d2d2c09e"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Michelle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff285b62-c02c-4fb6-8d61-cf3f4f19059a"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boss"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c42f86f7-de3c-40a1-8117-a57deb59c94d"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aj"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bc44c4d-0b1a-4d61-a5b5-2d3f852548da"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mremireh"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d7f5a53-72b1-43c0-a4ad-d677aa2aae23"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ty"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GrowMap"",
            ""id"": ""9865e4c6-f71f-4d00-b830-f256ec7046b8"",
            ""actions"": [
                {
                    ""name"": ""GrowingStuate"",
                    ""type"": ""Button"",
                    ""id"": ""de04f6af-6bfb-475e-8272-35412cf260fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8e040b4a-f250-4ae2-bb76-611438f179eb"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrowingStuate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMain
        m_PlayerMain = asset.FindActionMap("PlayerMain", throwIfNotFound: true);
        m_PlayerMain_Move = m_PlayerMain.FindAction("Move", throwIfNotFound: true);
        m_PlayerMain_Look = m_PlayerMain.FindAction("Look", throwIfNotFound: true);
        m_PlayerMain_Fire = m_PlayerMain.FindAction("Fire", throwIfNotFound: true);
        m_PlayerMain_Jump = m_PlayerMain.FindAction("Jump", throwIfNotFound: true);
        m_PlayerMain_Skate = m_PlayerMain.FindAction("Skate", throwIfNotFound: true);
        m_PlayerMain_Run = m_PlayerMain.FindAction("Run", throwIfNotFound: true);
        m_PlayerMain_Sword = m_PlayerMain.FindAction("Sword", throwIfNotFound: true);
        m_PlayerMain_ExtraSpeed = m_PlayerMain.FindAction("ExtraSpeed", throwIfNotFound: true);
        // CharacterMenuInput
        m_CharacterMenuInput = asset.FindActionMap("CharacterMenuInput", throwIfNotFound: true);
        m_CharacterMenuInput_Stick = m_CharacterMenuInput.FindAction("Stick", throwIfNotFound: true);
        m_CharacterMenuInput_Spartacus = m_CharacterMenuInput.FindAction("Spartacus", throwIfNotFound: true);
        m_CharacterMenuInput_Glassy = m_CharacterMenuInput.FindAction("Glassy", throwIfNotFound: true);
        m_CharacterMenuInput_Dobby = m_CharacterMenuInput.FindAction("Dobby", throwIfNotFound: true);
        m_CharacterMenuInput_Guard = m_CharacterMenuInput.FindAction("Guard", throwIfNotFound: true);
        m_CharacterMenuInput_Lusth = m_CharacterMenuInput.FindAction("Lusth", throwIfNotFound: true);
        m_CharacterMenuInput_Eve = m_CharacterMenuInput.FindAction("Eve", throwIfNotFound: true);
        m_CharacterMenuInput_Michelle = m_CharacterMenuInput.FindAction("Michelle", throwIfNotFound: true);
        m_CharacterMenuInput_Boss = m_CharacterMenuInput.FindAction("Boss", throwIfNotFound: true);
        m_CharacterMenuInput_Aj = m_CharacterMenuInput.FindAction("Aj", throwIfNotFound: true);
        m_CharacterMenuInput_Mremireh = m_CharacterMenuInput.FindAction("Mremireh", throwIfNotFound: true);
        m_CharacterMenuInput_Ty = m_CharacterMenuInput.FindAction("Ty", throwIfNotFound: true);
        // GrowMap
        m_GrowMap = asset.FindActionMap("GrowMap", throwIfNotFound: true);
        m_GrowMap_GrowingStuate = m_GrowMap.FindAction("GrowingStuate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMain
    private readonly InputActionMap m_PlayerMain;
    private IPlayerMainActions m_PlayerMainActionsCallbackInterface;
    private readonly InputAction m_PlayerMain_Move;
    private readonly InputAction m_PlayerMain_Look;
    private readonly InputAction m_PlayerMain_Fire;
    private readonly InputAction m_PlayerMain_Jump;
    private readonly InputAction m_PlayerMain_Skate;
    private readonly InputAction m_PlayerMain_Run;
    private readonly InputAction m_PlayerMain_Sword;
    private readonly InputAction m_PlayerMain_ExtraSpeed;
    public struct PlayerMainActions
    {
        private @Player m_Wrapper;
        public PlayerMainActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerMain_Move;
        public InputAction @Look => m_Wrapper.m_PlayerMain_Look;
        public InputAction @Fire => m_Wrapper.m_PlayerMain_Fire;
        public InputAction @Jump => m_Wrapper.m_PlayerMain_Jump;
        public InputAction @Skate => m_Wrapper.m_PlayerMain_Skate;
        public InputAction @Run => m_Wrapper.m_PlayerMain_Run;
        public InputAction @Sword => m_Wrapper.m_PlayerMain_Sword;
        public InputAction @ExtraSpeed => m_Wrapper.m_PlayerMain_ExtraSpeed;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMain; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMainActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerMainActions instance)
        {
            if (m_Wrapper.m_PlayerMainActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnMove;
                @Look.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnLook;
                @Fire.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFire;
                @Fire.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFire;
                @Fire.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFire;
                @Jump.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnJump;
                @Skate.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnSkate;
                @Skate.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnSkate;
                @Skate.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnSkate;
                @Run.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnRun;
                @Sword.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnSword;
                @Sword.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnSword;
                @Sword.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnSword;
                @ExtraSpeed.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnExtraSpeed;
                @ExtraSpeed.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnExtraSpeed;
                @ExtraSpeed.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnExtraSpeed;
            }
            m_Wrapper.m_PlayerMainActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Fire.started += instance.OnFire;
                @Fire.performed += instance.OnFire;
                @Fire.canceled += instance.OnFire;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Skate.started += instance.OnSkate;
                @Skate.performed += instance.OnSkate;
                @Skate.canceled += instance.OnSkate;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Sword.started += instance.OnSword;
                @Sword.performed += instance.OnSword;
                @Sword.canceled += instance.OnSword;
                @ExtraSpeed.started += instance.OnExtraSpeed;
                @ExtraSpeed.performed += instance.OnExtraSpeed;
                @ExtraSpeed.canceled += instance.OnExtraSpeed;
            }
        }
    }
    public PlayerMainActions @PlayerMain => new PlayerMainActions(this);

    // CharacterMenuInput
    private readonly InputActionMap m_CharacterMenuInput;
    private ICharacterMenuInputActions m_CharacterMenuInputActionsCallbackInterface;
    private readonly InputAction m_CharacterMenuInput_Stick;
    private readonly InputAction m_CharacterMenuInput_Spartacus;
    private readonly InputAction m_CharacterMenuInput_Glassy;
    private readonly InputAction m_CharacterMenuInput_Dobby;
    private readonly InputAction m_CharacterMenuInput_Guard;
    private readonly InputAction m_CharacterMenuInput_Lusth;
    private readonly InputAction m_CharacterMenuInput_Eve;
    private readonly InputAction m_CharacterMenuInput_Michelle;
    private readonly InputAction m_CharacterMenuInput_Boss;
    private readonly InputAction m_CharacterMenuInput_Aj;
    private readonly InputAction m_CharacterMenuInput_Mremireh;
    private readonly InputAction m_CharacterMenuInput_Ty;
    public struct CharacterMenuInputActions
    {
        private @Player m_Wrapper;
        public CharacterMenuInputActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Stick => m_Wrapper.m_CharacterMenuInput_Stick;
        public InputAction @Spartacus => m_Wrapper.m_CharacterMenuInput_Spartacus;
        public InputAction @Glassy => m_Wrapper.m_CharacterMenuInput_Glassy;
        public InputAction @Dobby => m_Wrapper.m_CharacterMenuInput_Dobby;
        public InputAction @Guard => m_Wrapper.m_CharacterMenuInput_Guard;
        public InputAction @Lusth => m_Wrapper.m_CharacterMenuInput_Lusth;
        public InputAction @Eve => m_Wrapper.m_CharacterMenuInput_Eve;
        public InputAction @Michelle => m_Wrapper.m_CharacterMenuInput_Michelle;
        public InputAction @Boss => m_Wrapper.m_CharacterMenuInput_Boss;
        public InputAction @Aj => m_Wrapper.m_CharacterMenuInput_Aj;
        public InputAction @Mremireh => m_Wrapper.m_CharacterMenuInput_Mremireh;
        public InputAction @Ty => m_Wrapper.m_CharacterMenuInput_Ty;
        public InputActionMap Get() { return m_Wrapper.m_CharacterMenuInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterMenuInputActions set) { return set.Get(); }
        public void SetCallbacks(ICharacterMenuInputActions instance)
        {
            if (m_Wrapper.m_CharacterMenuInputActionsCallbackInterface != null)
            {
                @Stick.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnStick;
                @Stick.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnStick;
                @Stick.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnStick;
                @Spartacus.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnSpartacus;
                @Spartacus.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnSpartacus;
                @Spartacus.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnSpartacus;
                @Glassy.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnGlassy;
                @Glassy.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnGlassy;
                @Glassy.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnGlassy;
                @Dobby.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnDobby;
                @Dobby.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnDobby;
                @Dobby.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnDobby;
                @Guard.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnGuard;
                @Guard.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnGuard;
                @Guard.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnGuard;
                @Lusth.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnLusth;
                @Lusth.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnLusth;
                @Lusth.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnLusth;
                @Eve.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnEve;
                @Eve.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnEve;
                @Eve.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnEve;
                @Michelle.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnMichelle;
                @Michelle.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnMichelle;
                @Michelle.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnMichelle;
                @Boss.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnBoss;
                @Boss.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnBoss;
                @Boss.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnBoss;
                @Aj.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnAj;
                @Aj.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnAj;
                @Aj.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnAj;
                @Mremireh.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnMremireh;
                @Mremireh.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnMremireh;
                @Mremireh.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnMremireh;
                @Ty.started -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnTy;
                @Ty.performed -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnTy;
                @Ty.canceled -= m_Wrapper.m_CharacterMenuInputActionsCallbackInterface.OnTy;
            }
            m_Wrapper.m_CharacterMenuInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Stick.started += instance.OnStick;
                @Stick.performed += instance.OnStick;
                @Stick.canceled += instance.OnStick;
                @Spartacus.started += instance.OnSpartacus;
                @Spartacus.performed += instance.OnSpartacus;
                @Spartacus.canceled += instance.OnSpartacus;
                @Glassy.started += instance.OnGlassy;
                @Glassy.performed += instance.OnGlassy;
                @Glassy.canceled += instance.OnGlassy;
                @Dobby.started += instance.OnDobby;
                @Dobby.performed += instance.OnDobby;
                @Dobby.canceled += instance.OnDobby;
                @Guard.started += instance.OnGuard;
                @Guard.performed += instance.OnGuard;
                @Guard.canceled += instance.OnGuard;
                @Lusth.started += instance.OnLusth;
                @Lusth.performed += instance.OnLusth;
                @Lusth.canceled += instance.OnLusth;
                @Eve.started += instance.OnEve;
                @Eve.performed += instance.OnEve;
                @Eve.canceled += instance.OnEve;
                @Michelle.started += instance.OnMichelle;
                @Michelle.performed += instance.OnMichelle;
                @Michelle.canceled += instance.OnMichelle;
                @Boss.started += instance.OnBoss;
                @Boss.performed += instance.OnBoss;
                @Boss.canceled += instance.OnBoss;
                @Aj.started += instance.OnAj;
                @Aj.performed += instance.OnAj;
                @Aj.canceled += instance.OnAj;
                @Mremireh.started += instance.OnMremireh;
                @Mremireh.performed += instance.OnMremireh;
                @Mremireh.canceled += instance.OnMremireh;
                @Ty.started += instance.OnTy;
                @Ty.performed += instance.OnTy;
                @Ty.canceled += instance.OnTy;
            }
        }
    }
    public CharacterMenuInputActions @CharacterMenuInput => new CharacterMenuInputActions(this);

    // GrowMap
    private readonly InputActionMap m_GrowMap;
    private IGrowMapActions m_GrowMapActionsCallbackInterface;
    private readonly InputAction m_GrowMap_GrowingStuate;
    public struct GrowMapActions
    {
        private @Player m_Wrapper;
        public GrowMapActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @GrowingStuate => m_Wrapper.m_GrowMap_GrowingStuate;
        public InputActionMap Get() { return m_Wrapper.m_GrowMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GrowMapActions set) { return set.Get(); }
        public void SetCallbacks(IGrowMapActions instance)
        {
            if (m_Wrapper.m_GrowMapActionsCallbackInterface != null)
            {
                @GrowingStuate.started -= m_Wrapper.m_GrowMapActionsCallbackInterface.OnGrowingStuate;
                @GrowingStuate.performed -= m_Wrapper.m_GrowMapActionsCallbackInterface.OnGrowingStuate;
                @GrowingStuate.canceled -= m_Wrapper.m_GrowMapActionsCallbackInterface.OnGrowingStuate;
            }
            m_Wrapper.m_GrowMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GrowingStuate.started += instance.OnGrowingStuate;
                @GrowingStuate.performed += instance.OnGrowingStuate;
                @GrowingStuate.canceled += instance.OnGrowingStuate;
            }
        }
    }
    public GrowMapActions @GrowMap => new GrowMapActions(this);
    public interface IPlayerMainActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSkate(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnSword(InputAction.CallbackContext context);
        void OnExtraSpeed(InputAction.CallbackContext context);
    }
    public interface ICharacterMenuInputActions
    {
        void OnStick(InputAction.CallbackContext context);
        void OnSpartacus(InputAction.CallbackContext context);
        void OnGlassy(InputAction.CallbackContext context);
        void OnDobby(InputAction.CallbackContext context);
        void OnGuard(InputAction.CallbackContext context);
        void OnLusth(InputAction.CallbackContext context);
        void OnEve(InputAction.CallbackContext context);
        void OnMichelle(InputAction.CallbackContext context);
        void OnBoss(InputAction.CallbackContext context);
        void OnAj(InputAction.CallbackContext context);
        void OnMremireh(InputAction.CallbackContext context);
        void OnTy(InputAction.CallbackContext context);
    }
    public interface IGrowMapActions
    {
        void OnGrowingStuate(InputAction.CallbackContext context);
    }
}
